build:
  uri: https://github.com/gepaplexx/gp-openshift
  ref: develop
  contextDir: gp-test-app/serviceA
deploy:
  resources:
    requests:
      cpu: 250m
      memory: 400Mi
    limits:
      cpu: 750m
      memory: 800Mi
  readinessProbe:
  livenessProbe:
  applicationProperties:
    enabled: true
    properties: |-
      quarkus.http.cors=true
      serviceB.baseURL=http://service-b.test-ns-b:8080
      serviceA2.baseURL=http://service-a2.jagertracing:8080
      quarkus.jaeger.service-name=service-a
      quarkus.jaeger.endpoint=http://jaeger-all-in-one-inmemory-collector:14268/api/traces
      quarkus.jaeger.sampler-type=const
      quarkus.jaeger.sampler-param=1
      quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId},parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n